name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Unit Test Permissions
      run: chmod -R 777 storage vendor/bin
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
      
    
# deploy:
#     name: 🚀 Deploy website on push
#     runs-on: ubuntu-latest
#     steps: 
#       - name: Checkout repository
#         uses: actions/checkout@main
#       - name: Sync files to hosting
#         uses: SamKirkland/FTP-Deploy-Action@4.0.0
#         with: 
#           server: ftp.server =>  get this in cpanel Configuration  ftp account
#           username: ftp_github@go-jobber.com  =>  get this in cpanel Configuration  ftp account
#           password: ${{ secrets.FTP_PASSWORD }} =>  get this in cpanel Configuration  ftp account password and copy this password
#                                           in 1)Actions secrets and variables
#                                             2)create New repository secret and name = its up to you FTP_Password
#                                             3) password =  past this password in   cpanel Configuration 
